models:
  - type: main
    engine: chatgroq
    model: llama-3.3-70b-versatile
    parameters:
      max_tokens: 300

rails:
  input:
    flows:
      - self check input


  output:
    flows:
      - self check output
